### ISSUE TITLE
Marked as deprecated on Thunderstore

### ISSUE THREAD

**Issue by Expakun** [Goorakh/CaptainBeaconFix#1]
For Some Reason, this mod is marked as deprecated on Thunderstore even though it works perfectly fine (at least for me) and there is no alternative for this mod.

**Comment by Goorakh** [comment]
The mod is deprecated because it is no longer needed, the bug was fixed as an undocumented change in ror2 version 1.2.4.4

**Comment by Expakun** [comment]
> The mod is deprecated because it is no longer needed, the bug was fixed as an undocumented change in ror2 version 1.2.4.4

It is still happening for me

**Comment by Goorakh** [comment]
Unlike the mod, the official fix only applies when you exit the drop pod, not when you spawn.

**Comment by Expakun** [comment]
> Unlike the mod, the official fix only applies when you exit the drop pod, not when you spawn.

ok thanks that explains it I have a mod that disables the Drop Pot
